version: '3.8'

services:
  ai_model_server:
    image: ai_model_server
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    ports:
      - "8000:8000"
      - "7483:7483"
    volumes:
      - type: bind
        source: C:/Example/Media/Images/Folder
        target: /media/images/folder
        read_only: true
      - type: bind
        source: C:/Example/Media/Images/Folder2
        target: /media/images/folder2
        read_only: true
      - "./:/app"
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
