name: ai_model_server
channels:
  - defaults
dependencies:
  - python=3.12
  - pip
  - pip:
    - -r requirements.txt
    - ./dist/ai_processing-0.0.0-cp312-cp312-win_amd64.whl  # [win]
    - wmi
    - windows-curses