name: ai_model_server
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip
  - pip:
    - ./dist/ai_processing-0.0.0-cp312-cp312-macosx_11_0_arm64.whl # [mac]
    - -r requirements-mac.txt
