type: model
model_file_name: magic_lake
model_license_name: licenseV2.0
model_threshold: 0.5
model_return_tags: True
max_queue_size: 32
max_batch_size: 32
max_model_batch_size: 32
instance_count: 1
max_batch_waits: 3