inputs:
  - image_path
output: result
short_name: im_giddy
version: 1.0

models:
  - name: image_preprocessor
    inputs:
      - image_path
    outputs:
      - preprocessed_image
  - name: giddy_music
    inputs:
      - preprocessed_image
    outputs:
      - actions
  - name: result_coalescer
    inputs:
      - actions
    outputs:
      - result