inputs:
  - image_path
  - threshold
  - return_confidence
output: result
short_name: actiondetection
version: 2.0

models:
  - name: image_preprocessor384
    inputs:
      - image_path
    outputs:
      - preprocessed_image
  - name: magic_lake
    inputs:
      - preprocessed_image
      - threshold
      - return_confidence
    outputs:
      - actions
  - name: result_coalescer
    inputs:
      - actions
    outputs:
      - result