inputs:
  - video_path
  - return_timestamps
  - time_interval
  - threshold
  - return_confidence
  - vr_video
output: results
short_name: actiondetection
version: 1.0

models:
  - name: video_preprocessor
    inputs:
      - video_path
      - return_timestamps
      - time_interval
      - threshold
      - return_confidence
      - vr_video
    outputs:
      - children
      - preprocessed_image
      - frame_index
      - threshold
      - return_confidence
  - name: giddy_music
    inputs:
      - preprocessed_image
      - threshold
      - return_confidence
    outputs:
      - actions
  - name: result_coalescer
    inputs:
      - frame_index
      - actions
    outputs:
      - result
  - name: result_finisher
    inputs:
      - result
    outputs: []
  - name: batch_awaiter
    inputs:
      - children
    outputs:
      - childrenResults
  - name: video_result_postprocessor
    inputs:
      - childrenResults
    outputs:
      - results